### PR TITLE
QR codes of phonepe and googlepay for donations 

### PR DESCRIPTION
**Pull request by deepak4566**
qr codes of phonepe and googlepay for donations

### CODE REVIEW

**Comment by KiranPranay** [comment]
@deepak4566 Where are these pics integrated ?

**Comment by deepak4566** [comment]
in pics folder

**Comment by deepak4566** [comment]
these will be integrated in donate now page as the payment page not working

**Comment by KiranPranay** [comment]
@deepak4566 Okay, no worries.
But, <!DOCTYPE html>
                <head>
    <title>donate here through phonepay or googlepay</title></head>

    <body> this snippet is incorrectly implemented. Will fix it and merge 👍.

**Comment by deepak4566** [comment]
oh ok fine

**Comment by deepak4566** [comment]
Added classes should I need to add css also???

**Comment by KiranPranay** [comment]
@deepak4566 Yes sure

**Comment by deepak4566** [comment]
Changes not visible in website??

**Comment by KiranPranay** [comment]
@deepak4566 Have to pull in the server manually

**Comment by deepak4566** [comment]
Ooh ok

**Comment by KiranPranay** [comment]
@deepak4566 Done.

**Pull request merged**
